name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: '`yarn lint`'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run linters
        run: yarn lint
