name: Publish

# We should search around on semantic release github issues to see if there's any known issues with github actions running our publish command

on:
  push:
    branches:
      - master
      - next

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CARBON_BOT_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Validate formatting
        run: yarn format:check

      - name: Lint
        run: yarn lint

      - name: Test, collect coverage
        # we need the "-- --" to pass the options through yarn and lerna and back to yarn
        run: yarn test -- -- --maxWorkers=2 --ci --logHeapUsage --coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./packages/react/coverage/lcov.info"
          base-path: "packages/react"

      - name: Build
        run: yarn build

      - name: Publish
        env:
          GH_TOKEN: ${{ secrets.CARBON_BOT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn publish-npm
