name: Test

on: [push, pull_request]

jobs:
  test-react:
    name: Test React
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome89-ff86

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check git version
        run: |
          currentver="$(git version | cut -f3 -d" ")"
          requiredver="2.22.0"
          if [ "$(printf '%s\n' "$currentver" "$requiredver" | sort -V | head -n1)" = "$requiredver" ]; then
            sudo apt-get update
            sudo apt-get install git
            echo "A version of git higher or equal to ${requiredver} is requied. Updating"
          else
            echo "${currentver} is greater than or equal ${requiredver}"
          fi

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            react:
              - 'packages/react/**'

      - name: Cache dependencies
        uses: actions/cache@v2
        if: steps.changes.outputs.react == 'true'
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.changes.outputs.react == 'true'
        run: |
          yarn --frozen-lockfile
          yarn lerna run --stream postinstall
          yarn lerna link

      - name: Run Jest tests, collect coverage
        if: steps.changes.outputs.react == 'true'
        run: |
          cd packages/react
          yarn test:ci

      - name: Run Cypress tests, collect coverage
        if: steps.changes.outputs.react == 'true'
        run: |
          cd packages/react
          yarn test:e2e:ci
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          HEIGHT: 900
          WIDTH: 1680

      - name: Copy, combine, and report coverage
        if: steps.changes.outputs.react == 'true'
        run: |
          cd packages/react
          yarn reports

      - name: Coveralls
        uses: coverallsapp/github-action@master
        if: steps.changes.outputs.react == 'true'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: './packages/react/coverage/lcov.info'
          base-path: 'packages/react'

  test-angular:
    name: Test Angular
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            angular:
              - 'packages/angular/**'

      - name: Use Node.js
        uses: actions/setup-node@v1
        if: steps.changes.outputs.angular == 'true'
        with:
          node-version: '14.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        if: steps.changes.outputs.angular == 'true'
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.changes.outputs.angular == 'true'
        run: |
          yarn --frozen-lockfile
          yarn lerna run --stream postinstall
          yarn lerna link

      - name: Run tests, collect coverage
        if: steps.changes.outputs.angular == 'true'
        run: |
          cd packages/angular
          yarn test:ci
