name: Test

on: [push, pull_request]

jobs:
  test:
    name: '`yarn test`'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run tests, collect coverage
        # we need the "-- --" to pass the options through yarn and lerna and back to yarn
        run: yarn test -- -- --maxWorkers=2 --ci --logHeapUsage --coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./packages/react/coverage/lcov.info"
          base-path: "packages/react"
